# Turn cronies (destinations) on or off.

standard-output: true
jabber: false
mail: false
campfire: false
trac: false
twitter: false

# Configurations for each destination. 
# You can delete or ignore ones you don't plan to use. 

jabber-account: jabber@example.com
jabber-password: not-the-real-one
jabber-to: 
    - brianmarick@example.com
    
mail-to: 
    - marick@example.com
    - dawn@example.com

mail-from: bmarick@mac.com
mail-server: smtp.mac.com
mail-port: 587
mail-from-domain: localhost.localdomain
mail-account: bmarick
mail-password: not-the-real-one
mail-authentication: login

campfire-login: marick@example.com
campfire-password: not-the-real-one
campfire-subdomain: example
campfire-room: room

twitter-login: twittername
twitter-password: some password
