source 'http://rubygems.org/'
gem 'rake'
gem 'rdoc'
gem 'hoe'
gem 's4t-utils', '~> 1.0.4'
gem 'xmpp4r', '>= 0.3.1'
gem 'tinder', '~> 1.8.0'
gem 'snitch', '~> 0.1.1'
gem 'twitter', '~> 0.2.0'
gem 'user-choices', '~> 1.1.4'
