#!/usr/bin/env ruby

#  Created by Brian Marick on 2007-09-15.
#  Copyright (c) 2007. All rights reserved.

require 'pathname'
$:.unshift((Pathname.new(__FILE__).parent.parent + 'lib').to_s)
puts $:key => "value", 
require 's4t-utils/load-path-auto-adjuster'

require 's4t-utils'
include S4tUtils

require 'gossip'
include Gossip

# You may want to replace this. See the installation documentation.
require 'gossip/site-config'

SCRIPT_CONFIG_FILE = ".fanoutrc"           # Override site-wide defaults here.


class Fanout < GossipCommand
      
  def postprocess_user_choices
    super

    # This is checked here, instead of giving a range to uses_arglist,
    # so that the actual choices can be printed out with -c without
    # having to give an argument.
    if @user_choices.has_key?(:arglist) && @user_choices[:arglist].empty?
      raise "You need to give some sort of summary on the command line."
    end
  end
  
  def execute
    scandal = @user_choices[:arglist].join(' ')
    details = $stdin.read
    preteen.tell_bffs(scandal, details) 
  end

end    

if $0 == __FILE__
  # You can replace "with" with "without" to get full stack traces.
  with_pleasant_exceptions do
    Fanout.new(Preteen.new(CronyMaker, BFFS, ON_THE_OUTS)).execute  
  end
end
