#!/usr/bin/env ruby
#
#  Created by Brian Marick on 2007-09-15.
#  Copyright (c) 2007. All rights reserved.

require 'pathname'
$:.unshift((Pathname.new(__FILE__).parent.parent + 'lib').to_s)
require 's4t-utils/load-path-auto-adjuster'

require 's4t-utils'
include S4tUtils

require 'gossip'
include Gossip

# You may want to replace this. See the installation documentation.
require 'gossip/site-config'
BFFS.delete(:trac) # Don't use this to post svn logs - trac does that better already.

require 'snitch'


class SvnTell < GossipCommand

  def script_config_file; ".svntellrc"; end
  
  def usage
    "Usage: ruby #{$0} --repository PATH --revision REV"
  end
  
  
  def add_choices_specific_to_script(builder)    
    builder.add_choice(:svn_repository) { | command_line |
      command_line.uses_option("--repository REP",
                               "Absolute path of subversion repository.")
    }

    builder.add_choice(:svn_revision) { | command_line |
      command_line.uses_option("--revision REV",
                               "Revision number of interest.")
    }

    svnlook_default = "/usr/bin/svnlook"
    builder.add_choice(:svnlook_path,
                       :default => svnlook_default) { | command_line |
      command_line.uses_option("--svnlook-path PATH",
                               "Absolute path of svnlook(1).",
                               "Default is #{svnlook_default}.")
    }
  end
  
  def execute
    svntext = Snitch::SvnLook.new(@user_choices[:svn_repository], 
                                  @user_choices[:svn_revision],
                                  @user_choices[:svnlook_path])
    preteen.tell_bffs('commit', svntext) 
  end

end    

if $0 == __FILE__
  # You can replace "with" with "without" to get full stack traces.
  without_pleasant_exceptions do
    SvnTell.new(Preteen.new(CronyMaker, BFFS, ON_THE_OUTS)).execute  
  end
end
